### ISSUE TITLE
Negative Ranges

### ISSUE THREAD

**Issue by Ritesh23** [thotro/arduino-dw1000#257] opened 2018-01-26 17:24 UTC
Hi All,

I am using the DWM1000 chips, one as an anchor and one as a tag and I am using the DW1000RANGING_TAG/ANCHOR examples, with no alterations to the code.

For some reason I am getting negative values for the range between the two chips, with the negative values decreasing as I move the tag closer to the anchor.

Here is an example of the output I am getting:

![image](https://user-images.githubusercontent.com/20907885/35452153-86daa8ba-02bd-11e8-8a05-df1d797c3467.png)

Could anyone help me understand why this issue is occurring?

Thank you.

**Comment by kuek** [comment] 2018-01-29 21:46
calibration is always a good start.

regards,
kuek from www.localino.net

**Comment by Ritesh23** [comment] 2018-01-29 22:04
Hi Kuek, thanks for the response.

I'm a beginner to wireless communications so I am unsure how to calibrate the DWM1000 chip. Do you know of any documentation or code which may be of help for calibration?

**Comment by Ritesh23** [comment] 2018-02-13 15:50
Hi @kuek 

Thanks for your response.

I am new to using these chips so I am not sure how to calibrate them.

Do you have any calibration code or documentation that may help?

Thank you.

Kind Regards,

Ritesh

**Comment by Rotzbua** [comment] 2018-02-18 16:32
Neg. ranges duplicate of #121

**Closed by Rotzbua** 2018-02-18 16:32 UTC
Labels: duplicate, invalid
