### ISSUE TITLE
Using library with EVB1000

### ISSUE THREAD

**Issue by agolovenko** [thotro/arduino-dw1000#61] opened 2016-02-02 17:48 UTC
Hi, I really appreciate your project. It's not an issue but more of a question. Is it possible to use this library for Arduino + EVB1000? 

I’ve  managed to connect SPI pins (SPICSn, SPIMOSI, SPIMISO, SPICLK) but couldn't find the way to connect RSTn and GPIO8. In fact I don't see RSTn and GPIO8 outputs on EVB1000 at all. Not sure how crucial are they in order the things to work properly (I'm kinda new to all this stuff). But anyway the basic example seemed to work while transmitter hangs.

Thanks, Ashot.

**Comment by ramdip** [comment] 2016-03-04 15:29
Hi, I've got the same problem. Did you find any kind of solution?
Help :( 
Thanks, Rams

**Comment by MikeS159** [comment] 2016-05-09 13:24
When you say the EVB100, do you mean [this](http://www.decawave.com/products/evk1000-evaluation-kit)?

What are you trying to do with an Arduino and one of these. They already come with a ARM processor, so you don't need an Arduino to go with them.

**Comment by ramdip** [comment] 2016-05-09 13:31
Hi, yes i used this Board. I try to work with arduino because i try to work
with Evb1000 without his arm processor. The arm processor is substitute
with Arduino... But it doesn't work. I think that the problem is the pin
reset.

Il lunedì 9 maggio 2016, MikeS159 <notifications@github.com> ha scritto:

> When you say the EVB100, do you mean this
> <http://www.decawave.com/products/evk1000-evaluation-kit>?
>
> What are you trying to do with an Arduino and one of these. They already
> come with a ARM processor, so you don't need an Arduino to go with them.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/thotro/arduino-dw1000/issues/61#issuecomment-217862739>
>


-- 
Ramona Di Pompeo

**Comment by MikeS159** [comment] 2016-05-10 08:21
Is there a reason you want to get rid of the ARM processor?

**Comment by ramdip** [comment] 2016-05-10 08:39
Yes... It is a project for the  university!

Il martedì 10 maggio 2016, MikeS159 <notifications@github.com> ha scritto:

> Is there a reason you want to get rid of the ARM processor?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/thotro/arduino-dw1000/issues/61#issuecomment-218090075>
>


-- 
Ramona Di Pompeo

**Comment by juwangvsu** [comment] 2016-09-01 21:55
on another note, if I program the anchor example to a dwm1000 + arduino mini pro, will it work with a evb1000 tag? 

I was testing such a setup with no result. But mine dwm1000 might have some bad soldering issues...

**Comment by abencomo** [comment] 2016-10-11 05:47
@juwangvsu, were you able to make the [DWM1000 + arduino mini pro](https://sites.google.com/site/wayneholder/uwb-ranging-with-the-decawave-dwm1000---part-ii/IMG_6229.JPG?attredirects=0) to work with the EVB1000 boards?

For my project, I'm installing the DWM1000 module on a small quadcopter and trying to use the EVB1000 boards as anchors for indoor location, but it's not able to receive or send data from/to anchors.

**Comment by juwangvsu** [comment] 2016-10-11 16:08
have not try that yet. I have some technical problems with dwm1000 + mini pro. it was working a few days ago: one programmed as RangingTag and the other programed with RangingAnchor, but not any more.
hopefully not hardware problem.

**Comment by abencomo** [comment] 2016-10-11 16:12
@all, has anyone be able to use a dwm1000+mini-pro to receive/send anchor distances from the EVB1000 boards using the thotro library?

**Comment by Rotzbua** [comment] 2017-04-26 11:06
@agolovenko Can I close this?

**Closed** 2018-03-25 15:09 UTC
Labels: hardware, will be closed
